from collections import Counter, defaultdict
from csv import DictReader, DictWriter
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "data" / "sample_corpus.csv"
RESULTS_DIR = ROOT / "results"
METRICS_FILE = RESULTS_DIR / "metrics.csv"
BIGRAMS_FILE = RESULTS_DIR / "top_bigrams.csv"
SUMMARY_FILE = RESULTS_DIR / "summary.md"

TOKEN_PATTERN = re.compile(r"[A-Za-z]+(?:'[A-Za-z]+)?")

STOPWORDS = {
    "a",
    "after",
    "alone",
    "and",
    "are",
    "as",
    "be",
    "before",
    "but",
    "by",
    "can",
    "each",
    "for",
    "got",
    "i",
    "in",
    "is",
    "it",
    "of",
    "the",
    "then",
    "that",
    "to",
    "we",
    "will",
}


def tokenize(text):
    return [match.group(0).lower() for match in TOKEN_PATTERN.finditer(text)]


def bigrams(tokens):
    return zip(tokens, tokens[1:])


def load_corpus():
    with DATA_FILE.open("r", encoding="utf-8", newline="") as file:
        return list(DictReader(file))


def register_metrics(register, documents):
    tokens = []
    for document in documents:
        tokens.extend(tokenize(document["text"]))

    token_count = len(tokens)
    type_count = len(set(tokens))
    hapax_count = sum(1 for count in Counter(tokens).values() if count == 1)
    content_tokens = [token for token in tokens if token not in STOPWORDS]

    return {
        "register": register,
        "documents": len(documents),
        "tokens": token_count,
        "types": type_count,
        "type_token_ratio": round(type_count / token_count, 3) if token_count else 0,
        "hapax_ratio": round(hapax_count / type_count, 3) if type_count else 0,
        "lexical_density": round(len(content_tokens) / token_count, 3) if token_count else 0,
    }


def top_bigrams(register, documents, limit=10):
    counts = Counter()
    for document in documents:
        tokens = tokenize(document["text"])
        counts.update(" ".join(pair) for pair in bigrams(tokens))

    return [
        {"register": register, "bigram": bigram, "count": count}
        for bigram, count in counts.most_common(limit)
    ]


def write_metrics(rows):
    fieldnames = [
        "register",
        "documents",
        "tokens",
        "types",
        "type_token_ratio",
        "hapax_ratio",
        "lexical_density",
    ]
    with METRICS_FILE.open("w", encoding="utf-8", newline="") as file:
        writer = DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_bigrams(rows):
    with BIGRAMS_FILE.open("w", encoding="utf-8", newline="") as file:
        writer = DictWriter(file, fieldnames=["register", "bigram", "count"])
        writer.writeheader()
        writer.writerows(rows)


def write_summary(metrics_rows, bigram_rows):
    lines = [
        "# Corpus Analysis Summary",
        "",
        "This file is generated by `scripts/analyze_corpus.py`.",
        "",
        "## Register Metrics",
        "",
        "| Register | Documents | Tokens | Types | TTR | Hapax Ratio | Lexical Density |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]

    for row in metrics_rows:
        lines.append(
            "| {register} | {documents} | {tokens} | {types} | {type_token_ratio} | {hapax_ratio} | {lexical_density} |".format(
                **row
            )
        )

    lines.extend(["", "## Top Bigrams", ""])

    for register in sorted({row["register"] for row in bigram_rows}):
        lines.append(f"### {register}")
        lines.append("")
        for row in [item for item in bigram_rows if item["register"] == register][:5]:
            lines.append(f"- `{row['bigram']}`: {row['count']}")
        lines.append("")

    SUMMARY_FILE.write_text("\n".join(lines), encoding="utf-8")


def main():
    if not DATA_FILE.exists():
        raise SystemExit(f"Missing corpus file: {DATA_FILE}")

    documents_by_register = defaultdict(list)
    for document in load_corpus():
        documents_by_register[document["register"]].append(document)

    RESULTS_DIR.mkdir(exist_ok=True)

    metrics_rows = [
        register_metrics(register, documents)
        for register, documents in sorted(documents_by_register.items())
    ]
    bigram_rows = []
    for register, documents in sorted(documents_by_register.items()):
        bigram_rows.extend(top_bigrams(register, documents))

    write_metrics(metrics_rows)
    write_bigrams(bigram_rows)
    write_summary(metrics_rows, bigram_rows)

    print(f"Wrote metrics to {METRICS_FILE}")
    print(f"Wrote bigrams to {BIGRAMS_FILE}")
    print(f"Wrote summary to {SUMMARY_FILE}")


if __name__ == "__main__":
    main()

